#!/bin/bash
# Sync known WiFi networks from NetworkManager into walter_c2.ino
# Generates the knownNetworks[] array from the host's saved connections.

NM_DIR="/etc/NetworkManager/system-connections"
SKETCH="$HOME/Arduino/walter_c2/walter_c2.ino"

if [ ! -d "$NM_DIR" ]; then
    echo "ERROR: NetworkManager connections not found at $NM_DIR"
    exit 1
fi

echo "// === Auto-generated by wifi-sync.sh $(date) ==="
echo "KnownNetwork knownNetworks[] = {"

first=true
for conn in "$NM_DIR"/*.nmconnection "$NM_DIR"/*; do
    [ -f "$conn" ] || continue
    
    ssid=$(sudo grep -m1 "^ssid=" "$conn" 2>/dev/null | cut -d= -f2)
    [ -z "$ssid" ] && continue
    
    psk=$(sudo grep -m1 "^psk=" "$conn" 2>/dev/null | cut -d= -f2)
    
    if $first; then first=false; else echo ","; fi
    printf '  {"%s", "%s"}' "$ssid" "$psk"
done

echo ""
echo "};"
echo "// === End auto-generated ==="
echo ""
echo "Paste this block into walter_c2.ino, replacing the existing knownNetworks[] array."
echo "Then recompile and flash."
